var caller =
{
	"GLOBAL": 0,
	"USER" : 1,
	"GUI" : 2
};

var actionMap ={};
actionMap[caller["GLOBAL"]] = { "GLOBAL" : 0 };
actionMap[caller["USER"]] = { "REGISTER" : 0, "MODIFY" : 1, "DATA" : 2, "BAN" : 3, "LOCK" : 4, "ACTIVATE" : 5, "REACTIVATE" : 6, "RECOVER_INIT" : 7, "RECOVER" : 8 };
actionMap[caller["GUI"]] = { "VERIFY_CREDENTIALS" : 0 };


var codeMap = {};
codeMap[caller["GLOBAL"]] = {};
codeMap[caller["GLOBAL"]][actionMap[caller["GLOBAL"]]["GLOBAL"]]  =  {"ERROR_NOT_AUTHENTICATED": 0, "ERROR_ACTION_UNKNOWN": 1, "ERROR_CALLER_UNKNOWN": 2, "ERROR_ONLY_POST_SUPPORTED": 3, "ERROR_INVALID_CREDENTIALS": 4, "ERROR_OBJECT_LOCKED": 5, "ERROR_RATE_LIMIT": 6, "ERROR_MISC_ERROR": 7};
codeMap[caller["USER"]] = {};
codeMap[caller["USER"]][actionMap[caller["USER"]]["REGISTER"]] = {"SUCCESSFULLY" : 0, "SUCCESSFULLY_LARS" : 1, "COUNTRY_NOT_FOUND" : 2, "CITY_TO_LONG" : 3, "CITY_EMPTY" : 4, "CITY_INVALID" : 5, "STATE_TO_LONG" : 6, "STATE_EMPTY" : 7, "STATE_INVALID" : 8, "STREET_TO_LONG" : 9, "STREET_EMPTY" : 10, "STREET_INVALID" : 11, "ZIPCODE_TO_LONG" : 12, "ZIPCODE_EMPTY" : 13, "ZIPCODE_INVALID" : 14, "BIRTH_DATE_INVALID" : 15, "SEX_INVALID" : 16, "LANGUAGE_NOT_FOUND" : 17, "PREREQUISITES_INVALID" : 18, "FAILED_CAPTCHA_INVALID" : 19, "USERNAME_TO_LONG" : 20, "USERNAME_EMPTY" : 21, "USERNAME_INVALID" : 22, "USERNAME_TAKEN" : 23, "FIRST_NAME_TO_LONG" : 24, "FIRST_NAME_EMPTY" : 25, "FIRST_NAME_INVALID" : 26, "LAST_NAME_TO_LONG" : 27, "LAST_NAME_EMPTY" : 28, "LAST_NAME_INVALID" : 29, "EMAIL_INVALID" : 30, "EMAIL_TAKEN" : 31, "FAILED_MISC" : 32 };
codeMap[caller["USER"]][actionMap[caller["USER"]]["MODIFY"]] = {"SUCCESSFULLY" : 0, "COUNTRY_NOT_FOUND" : 1, "CITY_TO_LONG" : 2, "CITY_EMPTY" : 3, "CITY_INVALID" : 4, "STATE_TO_LONG" : 5, "STATE_EMPTY" : 6, "STATE_INVALID" : 7, "STREET_TO_LONG" : 8, "STREET_EMPTY" : 9, "STREET_INVALID" : 10, "ZIPCODE_TO_LONG" : 11, "ZIPCODE_EMPTY" : 12, "ZIPCODE_INVALID" : 13, "BIRTH_DATE_INVALID" : 14, "SEX_INVALID" : 15, "LANGUAGE_NOT_FOUND" : 16, "PREREQUISITES_INVALID" : 17, "USERNAME_TO_LONG" : 18, "USERNAME_EMPTY" : 19, "USERNAME_INVALID" : 20, "USERNAME_TAKEN" : 21, "FIRST_NAME_TO_LONG" : 22, "FIRST_NAME_EMPTY" : 23, "FIRST_NAME_INVALID" : 24, "LAST_NAME_TO_LONG" : 25, "LAST_NAME_EMPTY" : 26, "LAST_NAME_INVALID" : 27, "EMAIL_INVALID" : 28, "EMAIL_TAKEN" : 29, "FAILED_MISC" : 30, "USER_NOT_FOUND" : 31, "NEEDS_REACTIVATION" : 32 };
codeMap[caller["USER"]][actionMap[caller["USER"]]["DATA"]] = {"SUCCESSFULLY" : 0, "USER_NOT_FOUND" : 1, "FAILED_MISC" : 2 };
codeMap[caller["USER"]][actionMap[caller["USER"]]["BAN"]] = {"SUCCESSFULLY" : 0, "USER_NOT_FOUND" : 1, "FAILED_MISC" : 2 };
codeMap[caller["USER"]][actionMap[caller["USER"]]["LOCK"]] = {"SUCCESSFULLY" : 0, "USER_NOT_FOUND" : 1, "FAILED_MISC" : 2 };
codeMap[caller["USER"]][actionMap[caller["USER"]]["ACTIVATE"]] = {"SUCCESSFULLY" : 0, "USER_NOT_FOUND" : 1, "INVALID_TOKEN" : 2, "FAILED_MISC" : 3 };
codeMap[caller["USER"]][actionMap[caller["USER"]]["REACTIVATE"]] = {"SUCCESSFULLY" : 0, "INVALID_TOKEN" : 1, "FAILED_MISC" : 2 };
codeMap[caller["USER"]][actionMap[caller["USER"]]["RECOVER_INIT"]] = {"SUCCESSFULLY" : 0, "USER_NOT_FOUND" : 1, "FAILED_MISC" : 2 };
codeMap[caller["USER"]][actionMap[caller["USER"]]["RECOVER"]] = {"SUCCESSFULLY" : 0, "TOKEN_TOO_OLD" : 1, "INVALID_TOKEN" : 2, "USER_NOT_FOUND" : 3, "FAILED_MISC" : 4 };
codeMap[caller["GUI"]] = {};
codeMap[caller["GUI"]][actionMap[caller["GUI"]]["VERIFY_CREDENTIALS"]] = {"SUCCESSFULLY" : 0, "UNSUCCESSFULLY" : 1, "FAILED_USER_NOT_FOUND" : 2, "FAILED_USER_NOT_AUTHENTICATED" : 3, "FAILED_USER_NOT_ACTIVATED" : 4, "FAILED_USER_NOT_ACTIVE" : 5, "FAILED_BRUTE_FORCE_ATTEMPT" : 6, "FAILED_WRONG_USER_OR_PASSWORD" : 7, "FAILED_MISSING_VALUES" : 8, "FAILED_MISC" : 9 };