angular.module('App.controllers', [])
    .controller("mainController", ['$scope', '$rootScope', 'uiCommunicateModel', '$state', '$stateParams', '$window', '$location', 'notificationManager', MainController])
    .controller("faqController", ['$scope','uiCommunicateModel', '$state','faqProps','$rootScope','$timeout', FaqController])
    .controller("faqDetailController", ['$scope','uiCommunicateModel', '$state', '$stateParams', 'faqProps', 'metatagFormatter', '$rootScope','$timeout',  FaqDetailController])
    .controller("newsController", ['$scope','uiCommunicateModel', '$rootScope', '$state', NewsController])
    .controller("newsDetailController", ['$scope','uiCommunicateModel', 'metatagFormatter', '$state', '$stateParams', '$rootScope', NewsDetailController])
    .controller("featureController", ['$scope','uiCommunicateModel', '$state', '$rootScope', FeatureController])
    .controller("featureDetailController", ['$scope','$rootScope', 'uiCommunicateModel', 'metatagFormatter', '$location', '$state', '$stateParams', FeatureDetailController])
    .controller("languageController", ['$scope', '$rootScope', 'uiCommunicateModel', '$state', '$location', LanguageController])
    .controller("navigationController", ['$scope','uiCommunicateModel', '$state', NavigationController])
    .controller("sidebarController", ['$scope','uiCommunicateModel', '$state', SidebarController])
    .controller("socialShareController", ['$scope','uiCommunicateModel', '$state', '$window', '$location', SocialShareController])
    .controller("sliderController", ['$scope','uiCommunicateModel', '$state', SliderController])
    .controller("supportController", ['$scope','uiCommunicateModel', '$rootScope', '$state', 'notificationManager', SupportController])
    .controller("registerController", ['$scope', '$rootScope', 'uiCommunicateModel', '$state', '$stateParams', '$window', 'notificationManager', RegisterController])
    .controller("passwordRecoveryController", ['$scope','uiCommunicateModel', '$state', '$scope', '$rootScope', PasswordRecoveryController])
    .controller("accountActivationController", ['$scope','uiCommunicateModel', '$rootScope', '$state', AccountActivationController])
    .controller("profileController", ['$scope', '$rootScope', 'uiCommunicateModel', '$state', '$window', 'notificationManager', ProfileController])
    .controller("gettingStartedController", ['$scope', '$rootScope', 'uiCommunicateModel', '$state', '$stateParams', GettingStartedController]);
