# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
from datetime import datetime


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User = apps.get_registered_model('auth', 'User')
    user = User.objects.get(username='masterchief')

    Language = apps.get_model("game", "Language")
    db_alias = schema_editor.connection.alias
    Language.objects.using(db_alias).bulk_create([
        Language(name="German",
                 creator=user,
                 created=datetime.utcnow().replace(tzinfo=utc),
                 editor=user,
                 edited=datetime.utcnow().replace(tzinfo=utc)),
        Language(name="English",
                 creator=user,
                 created=datetime.utcnow().replace(tzinfo=utc),
                 editor=user,
                 edited=datetime.utcnow().replace(tzinfo=utc)),
        Language(name="French",
                 creator=user,
                 created=datetime.utcnow().replace(tzinfo=utc),
                 editor=user,
                 edited=datetime.utcnow().replace(tzinfo=utc)),
        Language(name="Greek",
                 creator=user,
                 created=datetime.utcnow().replace(tzinfo=utc),
                 editor=user,
                 edited=datetime.utcnow().replace(tzinfo=utc)),
        Language(name="Italian",
                 creator=user,
                 created=datetime.utcnow().replace(tzinfo=utc),
                 editor=user,
                 edited=datetime.utcnow().replace(tzinfo=utc)),
        Language(name="Polnish",
                 creator=user,
                 created=datetime.utcnow().replace(tzinfo=utc),
                 editor=user,
                 edited=datetime.utcnow().replace(tzinfo=utc)),
        Language(name="Spanish",
                 creator=user,
                 created=datetime.utcnow().replace(tzinfo=utc),
                 editor=user,
                 edited=datetime.utcnow().replace(tzinfo=utc)),
        Language(name="Portuguese",
                 creator=user,
                 created=datetime.utcnow().replace(tzinfo=utc),
                 editor=user,
                 edited=datetime.utcnow().replace(tzinfo=utc))
    ])


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('world', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientSound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
                ('fading', models.FloatField(max_length=100.0, verbose_name='Fading in seconds')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator_amso', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_editor_amso', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('locations', models.ManyToManyField(to='world.Location')),
                ('seasons', models.ManyToManyField(to='world.Season')),
                ('weathers', models.ManyToManyField(to='world.Weather')),
            ],
            options={
                'verbose_name_plural': 'Ambient Sounds',
            },
        ),
        migrations.CreateModel(
            name='AmbientSoundGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=80)),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator_amsogr', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_editor_amsogr', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('sounds', models.ManyToManyField(to='game.AmbientSound')),
            ],
            options={
                'verbose_name_plural': 'Ambient Sound Groups',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Language name')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator_lang', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_editor_lang', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Start time')),
                ('time_end', models.TimeField(verbose_name='End time')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_creator_time', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_editor_time', to=settings.AUTH_USER_MODEL, verbose_name='Editor')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.AmbientSound', verbose_name='AmbientSound entry')),
            ],
            options={
                'verbose_name_plural': 'Times',
            },
        ),
        migrations.RunPython(forwards_func,),
    ]
