# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 10:06
from __future__ import unicode_literals

from datetime import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User = apps.get_registered_model('auth', 'User')
    user = User.objects.get(username='masterchief')

    Setting = apps.get_model("account", "Setting")
    SettingProfile = apps.get_model("account", "SettingProfile")
    Language = apps.get_model("game", "Language")

    db_alias = schema_editor.connection.alias

    lang = Language.objects.get(name='English')

    # Create profile settings
    SettingProfile.objects.using(db_alias).bulk_create([
        SettingProfile(name='Low',
                       creator=user,
                       created=datetime.utcnow().replace(tzinfo=utc),
                       editor=user,
                       edited=datetime.utcnow().replace(tzinfo=utc)
                       ),
        SettingProfile(name='Medium',
                       creator=user,
                       created=datetime.utcnow().replace(tzinfo=utc),
                       editor=user,
                       edited=datetime.utcnow().replace(tzinfo=utc)
                       ),
        SettingProfile(name='High',
                       creator=user,
                       created=datetime.utcnow().replace(tzinfo=utc),
                       editor=user,
                       edited=datetime.utcnow().replace(tzinfo=utc)
                       ),
        SettingProfile(name='Custom',
                       creator=user,
                       created=datetime.utcnow().replace(tzinfo=utc),
                       editor=user,
                       edited=datetime.utcnow().replace(tzinfo=utc)
                       ),
    ])

    # Create template settings
    Setting.objects.using(db_alias).bulk_create([
        Setting(distance=100,
                gamma=1.0,
                profileName='template low',
                width=0,
                height=0,
                fullscreen=True,
                vsync=False,
                reflection=False,
                parallax=False,
                motionBlur=False,
                refraction=False,
                volumetric=False,
                filter=False,
                resolution=6,
                occlusion=0,
                shader=0,
                texture=0,
                anisotropy=0,
                multisample=0,
                sfx=0,
                master=80.0,
                ambient=80.0,
                music=80.0,
                voice=80.0,
                character=80.0,
                effects=80.0,
                mouse_sensitivity=2.0,
                language=lang,
                user=user,
                profile=SettingProfile.objects.get(name='Low'),
                creator=user,
                created=datetime.utcnow().replace(tzinfo=utc),
                editor=user,
                edited=datetime.utcnow().replace(tzinfo=utc)),
        Setting(distance=100,
                gamma=1.0,
                profileName='template medium',
                width=0,
                height=0,
                fullscreen=True,
                vsync=False,
                reflection=True,
                parallax=True,
                motionBlur=False,
                refraction=False,
                volumetric=False,
                filter=True,
                resolution=6,
                occlusion=1,
                shader=1,
                texture=1,
                anisotropy=1,
                multisample=1,
                sfx=0,
                master=80.0,
                ambient=80.0,
                music=80.0,
                voice=80.0,
                character=80.0,
                effects=80.0,
                mouse_sensitivity=2.0,
                language=lang,
                user=user,
                profile=SettingProfile.objects.get(name='Medium'),
                creator=user,
                created=datetime.utcnow().replace(tzinfo=utc),
                editor=user,
                edited=datetime.utcnow().replace(tzinfo=utc)),
        Setting(distance=100,
                gamma=1.0,
                profileName='template high',
                width=0,
                height=0,
                fullscreen=True,
                vsync=False,
                reflection=True,
                parallax=True,
                motionBlur=False,
                refraction=False,
                volumetric=False,
                filter=True,
                resolution=6,
                occlusion=3,
                shader=2,
                texture=2,
                anisotropy=4,
                multisample=4,
                sfx=0,
                master=80.0,
                ambient=80.0,
                music=80.0,
                voice=80.0,
                character=80.0,
                effects=80.0,
                mouse_sensitivity=2.0,
                language=lang,
                user=user,
                profile=SettingProfile.objects.get(name='High'),
                creator=user,
                created=datetime.utcnow().replace(tzinfo=utc),
                editor=user,
                edited=datetime.utcnow().replace(tzinfo=utc)),
    ])

    tmpProfile = SettingProfile.objects.get(name='Low')
    tmpProfile.setting = Setting.objects.get(profileName='template low')
    tmpProfile.save()

    tmpProfile = SettingProfile.objects.get(name='Medium')
    tmpProfile.setting = Setting.objects.get(profileName='template medium')
    tmpProfile.save()

    tmpProfile = SettingProfile.objects.get(name='High')
    tmpProfile.setting = Setting.objects.get(profileName='template high')
    tmpProfile.save()


class Migration(migrations.Migration):
    dependencies = [
        ('game', '0001_initial'),
        ('world', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('SET CONSTRAINTS ALL IMMEDIATE',
                          reverse_sql=migrations.RunSQL.noop),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='world.Location',
                                    verbose_name='Current location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='language',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='linked_profile', to='account.SettingProfile', verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='settingprofile',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='linked_setting', to='account.Setting'),
        ),
        migrations.RunPython(forwards_func, ),
    ]
