# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('last_check', models.DateTimeField(verbose_name='Last check')),
            ],
            options={
                'verbose_name_plural': 'Server state',
            },
        ),
    ]
