# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import project.world.models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='logo',
            field=models.ImageField(default='None', upload_to=project.world.models.UploadToPathAndRename('images/location'), verbose_name='Location logo'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='image',
            field=models.ImageField(default='None', upload_to=project.world.models.UploadToPathAndRename('images/resouce'), verbose_name='Spawn map'),
        ),
    ]
