# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterCreate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False, verbose_name='Create date')),
                ('character', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.Character', verbose_name='Character')),
            ],
            options={
                'verbose_name_plural': 'Character creates',
            },
        ),
        migrations.CreateModel(
            name='CharacterJoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False, verbose_name='Login date')),
                ('character', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.Character', verbose_name='Character')),
            ],
            options={
                'verbose_name_plural': 'Character joins',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False, verbose_name='Send date')),
                ('message', models.TextField(editable=False, verbose_name='Message')),
                ('character', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.Character', verbose_name='Character')),
            ],
            options={
                'verbose_name_plural': 'Messages sent',
            },
        ),
        migrations.CreateModel(
            name='LauncherDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False, verbose_name='Send date')),
                ('release', models.TextField(editable=False, verbose_name='Release')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Launcher downloads',
            },
        ),
        migrations.CreateModel(
            name='PlayDuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(editable=False, null=True, verbose_name='Duration')),
                ('character', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='account.Character', verbose_name='Character')),
                ('join', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='stats.CharacterJoin', verbose_name='Join object')),
            ],
            options={
                'verbose_name_plural': 'Play durations',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False, verbose_name='Login date')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User logins',
            },
        ),
    ]
