# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 17:05
from __future__ import unicode_literals

from datetime import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User = apps.get_registered_model('auth', 'User')
    user = User.objects.get(username='masterchief')

    Channel = apps.get_model("communication", "Channel")
    Right = apps.get_model("communication", "Right")

    db_alias = schema_editor.connection.alias

    # Create basic channels
    Channel.objects.using(db_alias).bulk_create([
        Channel(name='sync', creator=user, created=datetime.utcnow().replace(tzinfo=utc), editor=user,
                edited=datetime.utcnow().replace(tzinfo=utc)),
        Channel(name='general', creator=user, created=datetime.utcnow().replace(tzinfo=utc), editor=user,
                edited=datetime.utcnow().replace(tzinfo=utc)),
    ])

    # Create rights
    Right.objects.using(db_alias).bulk_create([
        Right(name='join', creator=user, created=datetime.utcnow().replace(tzinfo=utc), editor=user,
              edited=datetime.utcnow().replace(tzinfo=utc)),
        Right(name='write', creator=user, created=datetime.utcnow().replace(tzinfo=utc), editor=user,
              edited=datetime.utcnow().replace(tzinfo=utc))
    ])


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=32, verbose_name='Internal channel id')),
                ('name', models.CharField(max_length=32, verbose_name='Channel name')),
                ('motd', models.CharField(max_length=512, verbose_name='Message of the day')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='user_creator_chan', to=settings.AUTH_USER_MODEL,
                                              verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='user_editor_chan', to=settings.AUTH_USER_MODEL,
                                             verbose_name='Editor')),
            ],
            options={
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='ChannelRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Channel',
                                              verbose_name='Channel')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Character',
                                                verbose_name='Character with permission')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='user_creator_chanri', to=settings.AUTH_USER_MODEL,
                                              verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='user_editor_chanri', to=settings.AUTH_USER_MODEL,
                                             verbose_name='Editor')),
            ],
            options={
                'verbose_name_plural': 'Channel Rights',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Private'), (2, 'Guild'), (3, 'Global')])),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('subject', models.CharField(max_length=32, verbose_name='Subject')),
                ('text', models.CharField(max_length=512, verbose_name='Text')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Character',
                                                verbose_name='Character')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='user_creator_evt', to=settings.AUTH_USER_MODEL,
                                              verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='user_editor_evt', to=settings.AUTH_USER_MODEL,
                                             verbose_name='Editor')),
            ],
        ),
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(editable=False, null=True, verbose_name='Last seen')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Character',
                                                verbose_name='Character')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(editable=False, verbose_name='Date received/sent')),
                ('answered', models.BooleanField(default=False, verbose_name='Answered')),
                ('read', models.BooleanField(default=False, verbose_name='Read')),
                ('subject', models.CharField(max_length=32, verbose_name='Subject')),
                ('text', models.TextField(max_length=2048, verbose_name='Text')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='user_creator_mess', to=settings.AUTH_USER_MODEL,
                                              verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='user_editor_mess', to=settings.AUTH_USER_MODEL,
                                             verbose_name='Editor')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver',
                                               to='account.Character', verbose_name='Received by')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender',
                                             to='account.Character', verbose_name='Sent by')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Information'), (2, 'Important')])),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('subject', models.CharField(max_length=32, verbose_name='Subject')),
                ('text', models.CharField(max_length=512, verbose_name='Text')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Character',
                                                verbose_name='Character')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='user_creator_not', to=settings.AUTH_USER_MODEL,
                                              verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='user_editor_not', to=settings.AUTH_USER_MODEL,
                                             verbose_name='Editor')),
            ],
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('created', models.DateTimeField(editable=False, verbose_name='Created on')),
                ('edited', models.DateTimeField(editable=False, verbose_name='Edited on')),
                ('creator', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='user_creator_right', to=settings.AUTH_USER_MODEL,
                                              verbose_name='Creator')),
                ('editor', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE,
                                             related_name='user_editor_right', to=settings.AUTH_USER_MODEL,
                                             verbose_name='Editor')),
            ],
            options={
                'verbose_name_plural': 'Access Rights',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.Channel',
                                              verbose_name='Channel')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Character',
                                                verbose_name='Character')),
            ],
        ),
        migrations.AddField(
            model_name='channelright',
            name='rights',
            field=models.ManyToManyField(to='communication.Right', verbose_name='Access Rights'),
        ),
        migrations.RunPython(forwards_func, ),
    ]
