# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 12:32
from __future__ import unicode_literals
import uuid
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Channel = apps.get_model("communication", "Channel")

    channels = Channel.objects.filter()

    for channel in channels:
        if channel.uuid == '':
            channel.uuid = uuid.uuid4().hex
            channel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='uuid',
            field=models.CharField(default='5dfc0c76fd354e51837e6214f97b3862', editable=False, max_length=32, verbose_name='Internal channel id'),
        ),
        migrations.RunPython(forwards_func, ),
    ]
