# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 21:08
from __future__ import unicode_literals
import uuid
from django.db import migrations, models
import project.communication.models


class Migration(migrations.Migration):

    def forwards_func(apps, schema_editor):
        # We get the model from the versioned app registry;
        # if we directly import it, it'll be the wrong version
        Channel = apps.get_model("communication", "Channel")

        # Create basic channels
        chan = Channel.objects.get(name='storage')
        chan.uuid = uuid.uuid4().hex
        chan.save()

    dependencies = [
        ('communication', '0003_add_storage_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='uuid',
            field=models.CharField(default=project.communication.models.get_uuid, editable=False, max_length=32, verbose_name='Internal channel id'),
        ),
        migrations.RunPython(forwards_func, ),
    ]
